---
# Main orchestration playbook: snapshot → restore → dump → upload → teardown

- name: Export one DB from Aurora snapshot to S3
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../group_vars/all.yml
  collections:
    - amazon.aws

  tasks:
    # STEP 1: Discover snapshot details and prepare variables
    - name: Discover snapshot metadata and generate names
      import_role:
        name: rds_get_config
      tags: [discover]

    # STEP 2: Retrieve the credentials of DB from Secrets Manager
    - name: Retrieve the credentials of DB from Secrets Manager
      import_role:
        name: secrets_get
      tags: [credentials]

    # STEP 3: Restore snapshot
    - name: Restore snapshot
      import_role:
        name: rds_restore
      tags: [restore]

    # STEP 4: Dump target DB and upload to S3
    - name: Dump database and upload to S3
      import_role:
        name: rds_dump
      tags: [dump]

    # STEP 5: Upload to S3
    - name: Upload DB backup to S3
      import_role:
        name: s3_upload
      tags: [upload]

    # STEP 6: Teardown temporary resources
    - name: Delete temporary RDS instance
      import_role:
        name: rds_teardown
      tags: [teardown]
